// popup/field-labels.js — Thai display labels for PRB payload fields.
// Keep in sync with FIELD_LABELS in moto24's tracking-detail-dialog.tsx.

// eslint-disable-next-line no-unused-vars
const FIELD_LABELS = {
  customerPrefix: "คำนำหน้า",
  customerFirstName: "ชื่อ",
  customerLastName: "นามสกุล",
  customerPhone: "เบอร์โทร",
  chassisNumber: "เลขตัวถัง",
  marqueValue: "ยี่ห้อรถ",
  carColorValue: "สีรถ",
  carSize: "ขนาดเครื่องยนต์ (cc)",
  carTypeValue: "รหัสรถ (CarType)",
  cardId: "เลขบัตรประชาชน",
  cardTypeValue: "ประเภทบัตร",
  birthdate: "วันเกิด",
  nationType: "สัญชาติ",
  nationalityOTH: "สัญชาติ (อื่น)",
  address: "ที่อยู่ (บรรทัด 1)",
  changwat: "จังหวัด",
  amphur: "อำเภอ",
  tumbol: "ตำบล",
  zipcode: "รหัสไปรษณีย์",
  licenseTypeValue: "ทะเบียนรถ",
  licenseAValue: "ทะเบียน (หมวดตัวอักษร)",
  licenseBValue: "ทะเบียน (หมวดตัวเลข)",
  carChangwatCode: "ทะเบียน (จังหวัด)",
  useNAddress: "ที่อยู่ทะเบียนบ้าน (toggle)",
  nAddress: "ที่อยู่ตามทะเบียน",
  nChangwat: "จังหวัด (ทะเบียนบ้าน)",
  nAmphur: "อำเภอ (ทะเบียนบ้าน)",
  nTumbol: "ตำบล (ทะเบียนบ้าน)",
  nZipcode: "รหัสไปรษณีย์ (ทะเบียนบ้าน)",
  nTel: "เบอร์โทร (ทะเบียนบ้าน)",
};
